import { http, HttpResponse } from 'msw'
import { TVeggie, TVeggies } from '@libs/libs.types'

/*
    These veggies are generated by
    https://deepai.org/chat/free-chatgpt AI.
*/

const veggies: TVeggies = [
    {
        "category": "Leafy Greens",
        "veggies": [
            {
                "name": "Spinach",
                "title": "Fresh Spinach",
                "ingredients": ["Spinach", "Water", "Salt"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/spinach.jpg",
                "price": 2.99
            },
            {
                "name": "Kale",
                "title": "Organic Kale",
                "ingredients": ["Kale", "Water", "Olive Oil"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/kale.jpg",
                "price": 3.49
            },
            {
                "name": "Romaine Lettuce",
                "title": "Crisp Romaine Lettuce",
                "ingredients": ["Romaine Lettuce", "Dressing"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/romaine.jpg",
                "price": 1.99
            },
            {
                "name": "Arugula",
                "title": "Peppery Arugula",
                "ingredients": ["Arugula", "Parmesan", "Lemon"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/arugula.jpg",
                "price": 2.50
            },
            {
                "name": "Swiss Chard",
                "title": "Charming Swiss Chard",
                "ingredients": ["Swiss Chard", "Butter"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/swiss_chard.jpg",
                "price": 3.30
            },
            {
                "name": "Collard Greens",
                "title": "Savory Collard Greens",
                "ingredients": ["Collard Greens", "Vinegar"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/collard_greens.jpg",
                "price": 2.75
            },
            {
                "name": "Mustard Greens",
                "title": "Spicy Mustard Greens",
                "ingredients": ["Mustard Greens", "Garlic"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/mustard_greens.jpg",
                "price": 2.10
            },
            {
                "name": "Boston Lettuce",
                "title": "Tender Boston Lettuce",
                "ingredients": ["Boston Lettuce", "Olive Oil"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/boston_lettuce.jpg",
                "price": 1.80
            },
            {
                "name": "Endive",
                "title": "Chicory Endive",
                "ingredients": ["Endive", "Balsamic Vinegar"],
                "type": "Leafy Green",
                "imageUrl": "https://example.com/images/endive.jpg",
                "price": 2.40
            }
        ]
    },
    {
        "category": "Root Vegetables",
        "veggies": [
            {
                "name": "Carrot",
                "title": "Crunchy Carrot",
                "ingredients": ["Carrot", "Water", "Sugar"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/carrot.jpg",
                "price": 1.20
            },
            {
                "name": "Beet",
                "title": "Sweet Beet",
                "ingredients": ["Beet", "Vinegar"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/beet.jpg",
                "price": 2.10
            },
            {
                "name": "Radish",
                "title": "Spicy Radish",
                "ingredients": ["Radish"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/radish.jpg",
                "price": 1.50
            },
            {
                "name": "Turnip",
                "title": "Savory Turnip",
                "ingredients": ["Turnip", "Salt", "Butter"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/turnip.jpg",
                "price": 1.70
            },
            {
                "name": "Parsnip",
                "title": "Delicious Parsnip",
                "ingredients": ["Parsnip", "Honey"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/parsnip.jpg",
                "price": 2.20
            },
            {
                "name": "Sweet Potato",
                "title": "Sweet Potato",
                "ingredients": ["Sweet Potato", "Brown Sugar"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/sweet_potato.jpg",
                "price": 2.99
            },
            {
                "name": "Jicama",
                "title": "Crunchy Jicama",
                "ingredients": ["Jicama", "Lime"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/jicama.jpg",
                "price": 3.00
            },
            {
                "name": "Garlic",
                "title": "Robust Garlic",
                "ingredients": ["Garlic", "Olive Oil"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/garlic.jpg",
                "price": 0.99
            },
            {
                "name": "Onion",
                "title": "Sweet Onion",
                "ingredients": ["Onion", "Salt"],
                "type": "Root Vegetable",
                "imageUrl": "https://example.com/images/onion.jpg",
                "price": 0.80
            }
        ]
    },
    {
        "category": "Cruciferous",
        "veggies": [
            {
                "name": "Broccoli",
                "title": "Nutrient-Packed Broccoli",
                "ingredients": ["Broccoli", "Cheese"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/broccoli.jpg",
                "price": 1.99
            },
            {
                "name": "Cauliflower",
                "title": "Fluffy Cauliflower",
                "ingredients": ["Cauliflower", "Butter"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/cauliflower.jpg",
                "price": 2.79
            },
            {
                "name": "Brussels Sprouts",
                "title": "Roasted Brussels Sprouts",
                "ingredients": ["Brussels Sprouts", "Garlic"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/brussels_sprouts.jpg",
                "price": 3.50
            },
            {
                "name": "Cabbage",
                "title": "Green Cabbage",
                "ingredients": ["Cabbage", "Salt"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/cabbage.jpg",
                "price": 1.50
            },
            {
                "name": "Kohlrabi",
                "title": "Crunchy Kohlrabi",
                "ingredients": ["Kohlrabi", "Dip"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/kohlrabi.jpg",
                "price": 2.10
            },
            {
                "name": "Radish",
                "title": "Fresh Radish",
                "ingredients": ["Radish", "Olive Oil"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/radish.jpg",
                "price": 1.80
            },
            {
                "name": "Collard Greens",
                "title": "Savory Collard Greens",
                "ingredients": ["Collard Greens", "Vinegar"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/collard_greens.jpg",
                "price": 2.25
            },
            {
                "name": "Bok Choy",
                "title": "Fresh Bok Choy",
                "ingredients": ["Bok Choy", "Soy Sauce"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/bok_choy.jpg",
                "price": 2.95
            },
            {
                "name": "Broccolini",
                "title": "Delicate Broccolini",
                "ingredients": ["Broccolini", "Olive Oil"],
                "type": "Cruciferous",
                "imageUrl": "https://example.com/images/broccolini.jpg",
                "price": 3.25
            }
        ]
    },
    {
        "category": "Fruiting Vegetables",
        "veggies": [
            {
                "name": "Tomato",
                "title": "Juicy Tomato",
                "ingredients": ["Tomato", "Basil"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/tomato.jpg",
                "price": 0.99
            },
            {
                "name": "Bell Pepper",
                "title": "Sweet Bell Pepper",
                "ingredients": ["Bell Pepper", "Olive Oil"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/bell_pepper.jpg",
                "price": 1.50
            },
            {
                "name": "Eggplant",
                "title": "Tender Eggplant",
                "ingredients": ["Eggplant", "Garlic"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/eggplant.jpg",
                "price": 2.25
            },
            {
                "name": "Zucchini",
                "title": "Fresh Zucchini",
                "ingredients": ["Zucchini", "Salt"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/zucchini.jpg",
                "price": 0.89
            },
            {
                "name": "Cucumber",
                "title": "Crunchy Cucumber",
                "ingredients": ["Cucumber", "Vinegar"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/cucumber.jpg",
                "price": 1.10
            },
            {
                "name": "Pumpkin",
                "title": "Seasonal Pumpkin",
                "ingredients": ["Pumpkin", "Spices"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/pumpkin.jpg",
                "price": 2.99
            },
            {
                "name": "Squash",
                "title": "Butternut Squash",
                "ingredients": ["Squash", "Brown Sugar"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/squash.jpg",
                "price": 2.50
            },
            {
                "name": "Melon",
                "title": "Sweet Melon",
                "ingredients": ["Melon", "Mint"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/melon.jpg",
                "price": 3.00
            },
            {
                "name": "Avocado",
                "title": "Creamy Avocado",
                "ingredients": ["Avocado", "Salt"],
                "type": "Fruiting",
                "imageUrl": "https://example.com/images/avocado.jpg",
                "price": 1.80
            }
        ]
    },
    {
        "category": "Legumes",
        "veggies": [
            {
                "name": "Green Beans",
                "title": "Fresh Green Beans",
                "ingredients": ["Green Beans", "Olive Oil"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/green_beans.jpg",
                "price": 1.50
            },
            {
                "name": "Peas",
                "title": "Sweet Peas",
                "ingredients": ["Peas", "Salt"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/peas.jpg",
                "price": 1.90
            },
            {
                "name": "Lentils",
                "title": "Nutritious Lentils",
                "ingredients": ["Lentils", "Water"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/lentils.jpg",
                "price": 2.00
            },
            {
                "name": "Chickpeas",
                "title": "Hearty Chickpeas",
                "ingredients": ["Chickpeas", "Olive Oil"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/chickpeas.jpg",
                "price": 2.50
            },
            {
                "name": "Kidney Beans",
                "title": "Rich Kidney Beans",
                "ingredients": ["Kidney Beans", "Onion"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/kidney_beans.jpg",
                "price": 3.00
            },
            {
                "name": "Black Beans",
                "title": "Savory Black Beans",
                "ingredients": ["Black Beans", "Cilantro"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/black_beans.jpg",
                "price": 2.40
            },
            {
                "name": "Pinto Beans",
                "title": "Creamy Pinto Beans",
                "ingredients": ["Pinto Beans", "Salsa"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/pinto_beans.jpg",
                "price": 2.20
            },
            {
                "name": "Soybeans",
                "title": "Nutritious Soybeans",
                "ingredients": ["Soybeans", "Salt"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/soybeans.jpg",
                "price": 2.75
            },
            {
                "name": "Mung Beans",
                "title": "Healthy Mung Beans",
                "ingredients": ["Mung Beans", "Lemon"],
                "type": "Legume",
                "imageUrl": "https://example.com/images/mung_beans.jpg",
                "price": 1.60
            }
        ]
    },
    {
        "category": "Squash",
        "veggies": [
            {
                "name": "Acorn Squash",
                "title": "Delicious Acorn Squash",
                "ingredients": ["Acorn Squash", "Maple Syrup"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/acorn_squash.jpg",
                "price": 2.30
            },
            {
                "name": "Spaghetti Squash",
                "title": "Unique Spaghetti Squash",
                "ingredients": ["Spaghetti Squash", "Olive Oil"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/spaghetti_squash.jpg",
                "price": 3.40
            },
            {
                "name": "Butternut Squash",
                "title": "Creamy Butternut Squash",
                "ingredients": ["Butternut Squash", "Nutmeg"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/butternut_squash.jpg",
                "price": 2.80
            },
            {
                "name": "Zucchini",
                "title": "Fresh Zucchini",
                "ingredients": ["Zucchini", "Garlic"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/zucchini.jpg",
                "price": 1.60
            },
            {
                "name": "Patty Pan Squash",
                "title": "Cute Patty Pan Squash",
                "ingredients": ["Patty Pan Squash", "Salt"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/patty_pan_squash.jpg",
                "price": 2.20
            },
            {
                "name": "Yellow Squash",
                "title": "Bright Yellow Squash",
                "ingredients": ["Yellow Squash", "Butter"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/yellow_squash.jpg",
                "price": 2.00
            },
            {
                "name": "Summer Squash",
                "title": "Seasonal Summer Squash",
                "ingredients": ["Summer Squash", "Herbs"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/summer_squash.jpg",
                "price": 3.10
            },
            {
                "name": "Kabocha Squash",
                "title": "Hearty Kabocha Squash",
                "ingredients": ["Kabocha Squash", "Cinnamon"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/kabocha_squash.jpg",
                "price": 2.50
            },
            {
                "name": "Hubbard Squash",
                "title": "Rich Hubbard Squash",
                "ingredients": ["Hubbard Squash", "Butter"],
                "type": "Squash",
                "imageUrl": "https://example.com/images/hubbard_squash.jpg",
                "price": 2.70
            }
        ]
    },
    {
        "category": "Alliums",
        "veggies": [
            {
                "name": "Onion",
                "title": "Savory Onion",
                "ingredients": ["Onion", "Vinegar"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/onion.jpg",
                "price": 1.20
            },
            {
                "name": "Garlic",
                "title": "Aromatic Garlic",
                "ingredients": ["Garlic", "Butter"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/garlic.jpg",
                "price": 0.99
            },
            {
                "name": "Leek",
                "title": "Sweet Leek",
                "ingredients": ["Leek", "Potato"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/leek.jpg",
                "price": 1.80
            },
            {
                "name": "Shallot",
                "title": "Delicate Shallot",
                "ingredients": ["Shallot", "Olive Oil"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/shallot.jpg",
                "price": 2.20
            },
            {
                "name": "Scallion",
                "title": "Fresh Scallion",
                "ingredients": ["Scallion", "Egg"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/scallion.jpg",
                "price": 1.10
            },
            {
                "name": "Green Onion",
                "title": "Crispy Green Onion",
                "ingredients": ["Green Onion", "Soy Sauce"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/green_onion.jpg",
                "price": 1.30
            },
            {
                "name": "Chives",
                "title": "Flavorful Chives",
                "ingredients": ["Chives", "Salad"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/chives.jpg",
                "price": 1.60
            },
            {
                "name": "Garlic Chives",
                "title": "Garlic Chives",
                "ingredients": ["Garlic Chives", "Noodles"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/garlic_chives.jpg",
                "price": 1.80
            },
            {
                "name": "Spring Onion",
                "title": "Fresh Spring Onion",
                "ingredients": ["Spring Onion", "Salad"],
                "type": "Allium",
                "imageUrl": "https://example.com/images/spring_onion.jpg",
                "price": 1.00
            }
        ]
    },
    {
        "category": "Stalk Vegetables",
        "veggies": [
            {
                "name": "Celery",
                "title": "Crisp Celery",
                "ingredients": ["Celery", "Peanut Butter"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/celery.jpg",
                "price": 0.80
            },
            {
                "name": "Asparagus",
                "title": "Tender Asparagus",
                "ingredients": ["Asparagus", "Olive Oil"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/asparagus.jpg",
                "price": 2.50
            },
            {
                "name": "Rhubarb",
                "title": "Tart Rhubarb",
                "ingredients": ["Rhubarb", "Sugar"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/rhubarb.jpg",
                "price": 2.70
            },
            {
                "name": "Fennel",
                "title": "Sweet Fennel",
                "ingredients": ["Fennel", "Vinegar"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/fennel.jpg",
                "price": 2.20
            },
            {
                "name": "Bamboo Shoots",
                "title": "Crispy Bamboo Shoots",
                "ingredients": ["Bamboo Shoots", "Salt"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/bamboo_shoots.jpg",
                "price": 3.00
            },
            {
                "name": "Leek",
                "title": "Savory Leek",
                "ingredients": ["Leek", "Potatoes"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/leek.jpg",
                "price": 1.50
            },
            {
                "name": "Coriander",
                "title": "Fragrant Coriander",
                "ingredients": ["Coriander"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/coriander.jpg",
                "price": 1.90
            },
            {
                "name": "Heart of Palm",
                "title": "Delicate Heart of Palm",
                "ingredients": ["Heart of Palm", "Salad"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/heart_of_palm.jpg",
                "price": 2.50
            },
            {
                "name": "Sorrel",
                "title": "Sour Sorrel",
                "ingredients": ["Sorrel", "Salad"],
                "type": "Stalk Vegetable",
                "imageUrl": "https://example.com/images/sorrel.jpg",
                "price": 1.70
            }
        ]
    }
]

function shuffleArray(arr: TVeggie[]) {
    return arr.reduce((acc: TVeggie[], item: TVeggie) => {
        const randomIndex = Math.floor(Math.random() * (arr.length + 1))
        return [...acc.slice(0, randomIndex), item, ...acc.slice(randomIndex)];
    }, [])
}

const wait = (delay: number = 1000) => new Promise(resolve => setTimeout(resolve, delay))

export const handlers = [
    http.get('/categories', async () => HttpResponse.json(veggies.map(v => v.category))),
    http.get('/specials', async() => {
        const _flat = veggies.map(v => v.veggies).flat();
        const _veggies = shuffleArray(_flat).slice(0, 6);
        await wait();
        return HttpResponse.json(_veggies);
    }),
    http.get('/veggies/:category', async ({ params: { category } }) => {
        const _veggies = veggies.find(v => v.category === category)?.veggies ?? [];
        const __veggies = shuffleArray(_veggies);
        await wait();
        return HttpResponse.json(__veggies);
        }
    ),
]
